language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

# Basic coding standard checks:
# - Uses spaces, not tabs.
# - No trailing whitespace.
before_install:
  - "if git grep -n $'\t'          *.cpp *.c *.hpp *.h; then echo 'Please replace tabs with spaces in source files.';     false; fi"
  - "if git grep -n '[[:blank:]]$' *.cpp *.c *.hpp *.h; then echo 'Please remove trailing whitespace from source files.'; false; fi"

script:
  - mkdir -p build
  - cd build
  - cmake -DENABLE_CLIPROF=1 ..
  - make -j 4
